export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SEARCH_DEVICE = 'searh_device';
export const GET_DEVICE_BY_CATEGORY = 'get_device_by_category';
export const SEARCH_CHANGE = 'search_change';
export const ADD_CART = 'add_cart';
export const GET_CART = 'get_cart';
export const UPDATE_CART = 'update_cart';
export const DELETE_CART = 'delete_cart';
export const DESTROY_CART = 'destroy_cart';


// devices
export const FETCH_DEVICES_HOME = 'FETCH_DEVICES_HOME';
export const FETCH_DEVICES_HOME_SUCCESS = 'FETCH_DEVICES_HOME_SUCCESS';
export const FETCH_DEVICES_HOME_FAILED = 'FETCH_DEVICES_HOME_FAILED';

export const FETCH_DEVICES_DETAIL = 'FETCH_DEVICES_DETAIL';
export const FETCH_DEVICES_DETAIL_SUCCESS = 'FETCH_DEVICES_DETAIL_SUCCESS';
export const FETCH_DEVICES_DETAIL_FAILED = 'FETCH_DEVICES_DETAIL_FAILED';

export const FETCH_DEVICES_BY_CATEGORY = 'FETCH_DEVICES_BY_CATEGORY';
export const FETCH_DEVICES_BY_CATEGORY_SUCCESS = 'FETCH_DEVICES_BY_CATEGORY_SUCCESS';
export const FETCH_DEVICES_BY_CATEGORY_FAILED = 'FETCH_DEVICES_BY_CATEGORY_FAILED';

export const FETCH_DEVICES_LIST = 'FETCH_DEVICES_LIST';
export const FETCH_DEVICES_LIST_SUCCESS = 'FETCH_DEVICES_LIST_SUCCESS';
export const FETCH_DEVICES_LIST_FAILED = 'FETCH_DEVICES_LIST_FAILED';

export const FETCH_DEVICES_SEARCH = 'FETCH_DEVICES_SEARCH';
export const FETCH_DEVICES_SEARCH_SUCCESS = 'FETCH_DEVICES_SEARCH_SUCCESS';
export const FETCH_DEVICES_SEARCH_FAILED = 'FETCH_DEVICES_SEARCH_FAILED';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
